---
#
# Ansible managed
#
repository:
  description: Upgrade a package only if it is installed otherwise do nothing.
  homepage: https://buluma.github.io/
  topics: upgrade, security, ansible, molecule, playbook
